### ISSUE TITLE
Single Episode Prev/Next arrow missing in mobile

### ISSUE THREAD

**Issue by farookibrahim** [Transvelo/vodi#370]

**Comment by anastransvelo** [comment]
https://demo2.madrasthemes.com/vodi-demos/main/episode/the-first-polaroid/

@media (max-width: 767.98px) {
.episode__player--next-episode, 
.episode__player--prev-episode {
    position: relative;
    display: block;
}

.single-episode-v3 .episode__player--arrows>*+*:before, 
.single-episode-v4 .episode__player--arrows>*+*:before {
    display: none;
}

.single-episode-v3 .episode__player--arrows, 
.single-episode-v4 .episode__player--arrows {
    display: block;
    width: 100%;
}

.single-episode-v3 .episode__player--prev-episode, 
.single-episode-v4 .episode__player--prev-episode {
    margin-bottom: 15px;
    border-bottom: 1px solid  #949cb0;
    padding-bottom: 15px;
}

.single-episode-v3 .episode__player--prev-episode a:before, 
.single-episode-v4 .episode__player--prev-episode a:before,
.single-episode-v3 .episode__player--next-episode a:after, 
.single-episode-v4 .episode__player--next-episode a:after {
    width: 30px;
    height: 30px;
}
}

**Comment by anastransvelo** [comment]
https://demo2.madrasthemes.com/vodi-demos/main/episode/tape-3-side-a/
https://gist.github.com/anastransvelo/fbd8da203a3433b5cc4e81b56a1ad6d2
